### ISSUE TITLE
Could 2160p support be added?

### ISSUE THREAD

**Issue by apsen-github** [cubicibo/SUPer#34]
Could 2160p support be added?

As far as I understand it only needs adding `HD2160    = (3840, 2160)` to `class VideoFormat(Enum):`

Thanks!

**Comment by cubicibo** [comment]
Hi,
PGS at 4K makes no sense whatsoever: the format is unsuited for that. UHD players cannot decode PGS beyond 1080p. UHD BD contain subtitles at 1080p, and the BD player upscales them to 2160p.

The PGS decoder memory is simply too small, the bitmap compression method inefficient, and the decoder speed too slow. It's just a waste of computational power and memory. You cannot achieve any typesetting effect and the file is only usable with *some* software players. Since typesetting becomes literally impossible at 2160p due to speed and memory, why would you even need the dialogue lines to be rendered in 4K?
