### ISSUE TITLE
SUPer creates empty 1 frame long entries

### ISSUE THREAD

**Issue by nautilus7** [cubicibo/SUPer#9]
Hi, I have a bdn/xml file which contains 1274 events/subtitles, but the output PGS contains 1288. These extra entries are empty images with a length of 1 frame. For example, in output file, entries 256, 266, 307, and more, are empty and should not be there.

This happens almost every time, whatever bdn/xml I try. The original file is an PGS from blu-ray, converted to bdn/xml with subtitleedit, edited the images, and then I fed it to SUPer. The output file SUPer creates contains these extra empty entries.

Example files attached. 

[sample.zip](https://github.com/cubicibo/SUPer/files/12570545/sample.zip)

**Comment by cubicibo** [comment]
Hi,
Can you be a bit more specific with your setup? Which version did you use? Was it the HEAD or a released executable (v0.2.0)? Besides, what do you mean by "entries in the output"? 0256.png? Or epoch 256? I don't follow what is your issue and I don't see any visual issue when I check your file at 0256.png timestamps, for example.
What do you mean by one frame long entry? What is your analysis exactly (with SubtitleEdit?)

If you mean there are more segments than events, this is normal. Especially if you use a recent version of HEAD (0b6c149be1266f9952f914ad680bb629d3ae252e or after). With PGS, redrawing the screen is bandwidth constrained on Blu-ray players. It would be an issue with animations, as up to 4 frames would be lost as the decoder is busy drawing (clearing the screen. However, updating the palette to hide the subtitle is not subject to bandwidth constraints.

As such, SUPer performs the following, when there is enough time between two subtitles [between epoch end and next epoch start]:
1. It flushes the palette at exactly OutTC. The subtitle is still there but invisible.
2. +4 frames after, the screen is cleared by the "expensive" drawing operation. This is only performed if two subtitles are more than 1.5 seconds apart.

**Comment by nautilus7** [comment]
Hi, I used the 0.2.0 release.

By "entries in the output", I mean the subtitles in the produced sup file. I get the numbering from subtitleedit. These subtitles  show as empty images in subtitlesedit, and other other SUP programs I use for OCR. These empty entries (in subtitleedit) have a duration of 42ms or 1 frame long when using 23.976 fps subs.

I don't really understand the technical analysis you do in your comment, but I haven't seen professionally made subs (coming from blu-rays) containing such "empty" events. At least for simple subtitles without any moving or fading effects, like those found at 99,99% of movies.

**Comment by cubicibo** [comment]
Thanks. I looked carefully at your file and this is not an issue, but the way SUPer encodes the stream.

Without being technical, PGS has something called "epoch". In epochs, the memory and window layout is constant. Each epoch must be separated by at least 2 to 6-7 frames in general.
Within a given epoch, there may be numerous subtitles separated by blanked screen. I.e.:
```
<Event InTC="00:28:24:01" OutTC="00:28:26:22" Forced="false">
  <Graphic Width="649" Height="61" X="636" Y="897">0221.png</Graphic>
</Event>
<Event InTC="00:28:26:23" OutTC="00:28:29:07" Forced="false">
  <Graphic Width="195" Height="50" X="859" Y="897">0222.png</Graphic>
</Event>
```
The two events are spaced by one frame in the same epoch.

To clear the screen between 00:28:26:22 and 00:28:26:23, there are two ways:
- The drawing operation. This is the common one. But it is expensive computationally for hardware decoders and works only for small subtitles.
- The palette update. They are very cheap computationally and will work for tiny or gigantic subtitles.

SUPer always performs palette updates to clear the screen, as this method is not subject to time constraints of hardware decoding.

When you analyze the output SUP file in SubtitleEdit, it sees the palette update operation (1 frame long event) and believes it is a new subtitle. But it is invisible to you because all colors are set to be YUV fully transparent black (16, 128 128, 0).

If you analyze the datastream, you will find exactly 14 palette update commands.
14 + 1274 = 1288.
The count is there. While it is strange to you, on playback, it will be 100% perfect to your eyes and match totally your BDN XML timing and visual quality.

**Comment by nautilus7** [comment]
Ok, I understand, thanks for the detailed explanation.

What happens if I delete these 14 palette update commands? Will be a problem (e.g. incompatibility with some devices) or even the subs will brake completely?

Why the original blu-ray pgs did not have these extra events? Does it use the drawing operation method to clear the screen perhaps?

Is it wrong for programs like subtitleedit to list these palette update commands as events? Are these signaled in some way, so they can be ignored and not listed as subtitle events?

Regards.

**Comment by cubicibo** [comment]
The subs will remain visible on screen until the next one appears. In this case it is a single frame, no one will notice.
I would recommend you to not delete these events if you intend the use the file on Blu-ray players.

Your PGS extracted from Blu-ray did not have these events because it is encoded differently. PGS is a very versatile (and complex) format, there are many ways to encode visually identical files.
And yes it must have used the drawing operation to clear the screen. The subtitles here are small (And not huge overlays taking half of the screen, which SUPer supports), it is OK.

As to SubtitleEdit and palette update commands: it is not wrong.
Palette updates can be used to display a new line in the same bitmap (transparent -> opaque), while another line remains displayed as it uses different colors. You do not want to miss such event.
Conversely, palette updates can also be used to fade in and fade out. Then, you do not want SubtitleEdit to count these as events.
I believe, SubtitleEdit has an option to merge similar captions when analysing SUP.

**Comment by nautilus7** [comment]
> And yes it must have used the drawing operation to clear the screen. The subtitles here are small (And not huge overlays taking half of the screen, which SUPer supports), it is OK.
> 

Would it be possible or easy to add an option for using the drawing operation to clear the screen in such cases? One could use it for simple subs like those found in regular movies, with no big cost for the hardware decoder, like you said.

Thanks for your time explaining.

**Comment by cubicibo** [comment]
Sorry but this is unlikely. This adds complexity in the code for no value. Most users also won't understand the difference of the checkbox on the GUI and misuse it. Also it adds testing for me...

But you can trust SUPer to produce files that are compatible with Blu-ray players, even if they do not follow the usual way of shaping the stream.

**Comment by cubicibo** [comment]
@nautilus7 With commit 72d9c6481dd9e37a6df31eda13b79978a95688cf and 0e80cfc573843fb924e32c5c10e26f8e50628a66, SUPer adaptively selects between redrawing operation or palette update to hide a subtitle. SUPer makes the decision automatically, depending on the size of the subtitle and how long it is on screen.

**Comment by nautilus7** [comment]
That's great! Will test soon and get back to you with feedback. Thanks for making this change!

**Comment by nautilus7** [comment]
Hi, when is the next version release planned, so I can test these changes?

**Comment by cubicibo** [comment]
Hi, I still want to fix one bug in PES+MUI output before eventually releasing v0.2.1a. Probably in one or two weeks.

**Comment by cubicibo** [comment]
@nautilus7 Please try: https://github.com/cubicibo/SUPer/releases/download/v0.2.1/win_x64_SUPer_v0.2.1a.7z

**Comment by nautilus7** [comment]
Hm, something weird is happening. While now the are exactly 1274 events like in the input xml file, their timings are off.

I tested with the same bdn/xml file as in first post (which I also attach in this post). The first events are off by a couple of frames but they progressively get more and more out of sync.
[test21a.zip](https://github.com/cubicibo/SUPer/files/12786030/test21a.zip)

**Comment by cubicibo** [comment]
I think I know: when you tried SUPer for the first time, you did not tick the NTSC timing checkbox.

Back in **v0.2.0**, the user had the responsability to tick the "NTSC timing" checkbox for 23.976, 29.97, 59.94 NDF. However this was stupid. NDF timecodes with NTSC FPS are not real time. Those timecodes must always be scaled by 1.001 when converted to timestamps, this is all defined in SMPTE 12M official doc. If your XML does not need scaling, then it is generated incorrectly.
So, in **v0.2.1**, I replaced the check box with code to perform automatic detection. For all XML with NTSC FPS, the timestamps are scaled by 1.001.

SubtitleEdit is responsible for generating proper XML timecodes. Else, ass2bdnxml will always produce perfect SMPTE timecodes.
An easy fix is simply to scale all timestamps by /1.001 in SubtitleEdit :)

**Comment by cubicibo** [comment]
Here's 0217.png appearing at XML defined time.
TC 00:27:28:15 (NTSC time) -> 00:27:30.274 (real time)
![mpv-shot0001](https://github.com/cubicibo/SUPer/assets/55701024/01253ec5-7e07-47f5-85bf-6b24527f7188)

Everything seems correct.

**Comment by nautilus7** [comment]
Oh, so the times inside the xml file are not the same with real time? Wasn't aware of that.

I am running again with a newly made xml...

**Comment by cubicibo** [comment]
`Oh, so the times inside the xml file are not the same with real time? Wasn't aware of that.`
Only for NTSC (fractional) framerates in Non-Drop Frame (NDF) mode. There exist "Drop Frame" NTSC timecodes which are real time, but they are generally unsupported by most softwares because of the complexity.

In any case, whenever you export 23.976, 29.97 or 59.94 content from SubtitleEdit to NDF BDN XML+PNG, you should not have to scale timestamps manually. So this is probably a SubtitleEdit issue.

**Comment by nautilus7** [comment]
Ok, so, I think subtitlesedit does NOT read the ntsc timings correctly when reading a bdn/xml file.

It seems SUPer works fine. But I think ass2bdnxml has a bug. The last xml entry created from the attached ass subtitle has wrong duration.

My workflow is ass -> bdn/xml with ass2bdnxml -> sup with SUPer
All files are attached. Can you check the last entry if it has the correct duration in the sup file? In the ass file it shows with a duration of 1000ms, but in the sup file it has a duration of 792ms

[test.zip](https://github.com/cubicibo/SUPer/files/12786649/test.zip)

**Comment by cubicibo** [comment]
Thanks, I will look into it in the next days.

**Comment by nautilus7** [comment]
Thank you too for making these changes to SUPer as well.

**Comment by cubicibo** [comment]
Many thanks for finding out this bad issue in ass2bdnxml. I have just fixed it and will release a new EXE later today.
[ass2bdnxml@1f025eb](https://github.com/cubicibo/ass2bdnxml/commit/1f025eb2d0f0544cdabfce38cc5bdf63f5c10e9b)
